[package]
name = "create_vox"
version = "0.1.0"
authors = ["Mickey Fraser <mickey_fraser@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
